version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: polling-postgres
    environment:
      POSTGRES_DB: realtime_polling_db
      POSTGRES_USER: polling_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polling_user -d realtime_polling_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
